version: '3.7'

services:
  registry:
    image: registry:2.7.1
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry
  caddy:
    image: mrzli/caddy-for-registry:1.0.1
    ports:
      - "80:80"
      - "443:443"
    environment:
      ACME_AGREE: "true"
      CADDYPATH: /etc/caddycerts
      CADDY_DOMAIN_NAME: private-packages.xyz
      CADDY_LETS_ENCRYPT_EMAIL: goran.mrzljak@gmail.com
      # CADDY_LETS_ENCRYPT_CA_URL: https://acme-staging-v02.api.letsencrypt.org/directory
      CADDY_LETS_ENCRYPT_CA_URL: https://acme-v02.api.letsencrypt.org/directory # for production
      CADDY_REGISTRY_HOST: registry
      # CADDY_REGISTRY_HOST: 138.68.92.239
      CADDY_REGISTRY_PORT: 5000
    volumes:
      - caddy-certs:/etc/caddycerts
      - caddy-caddy:/root/.caddy
      - caddy-srv:/srv

volumes:
  registry-data:
  caddy-certs:
  caddy-caddy:
  caddy-srv:

